package whatisnewin.javax.lang.model.util;

import javax.lang.model.util.SimpleTypeVisitor9;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link SimpleTypeVisitor9}
 * that were newly introduced in Java version 9.<br>
 *
 * {@link SimpleTypeVisitor9} is a completely new class.
 * @since 9
 * @see SimpleTypeVisitor9
 */
public final class WhatIsNewInSimpleTypeVisitor9<R, P>
{
}
