package whatisnewin.javax.lang.model.util;

import javax.lang.model.util.TypeKindVisitor9;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link TypeKindVisitor9}
 * that were newly introduced in Java version 9.<br>
 *
 * {@link TypeKindVisitor9} is a completely new class.
 * @since 9
 * @see TypeKindVisitor9
 */
public final class WhatIsNewInTypeKindVisitor9<R, P>
{
}
