package whatisnewin.java.lang;

import java.util.stream.IntStream;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link String}
 * that were newly introduced in Java version 9.<br>
 *
 * {@link String} is an old class but has new fields, constructors or methods.
 * @since 1.0
 * @see String
 */
public final class WhatIsNewInString
{
  /**
   * Example call to new method {@link String#codePoints()}.
   * @since 9
   * @see String#codePoints()
   */
  public IntStream codePoints()
  {
    String testee = $$$();

    IntStream result = testee.codePoints();
    return result;
  }

  /**
   * Example call to new method {@link String#chars()}.
   * @since 9
   * @see String#chars()
   */
  public IntStream chars()
  {
    String testee = $$$();

    IntStream result = testee.chars();
    return result;
  }

  private String $$$()
  {
    return null;
  }
}
