package whatisnewin.java.lang;


/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link Class}
 * that were newly introduced in Java version 9.<br>
 *
 * {@link Class} is an old class but has new fields, constructors or methods.
 * @since 1.0
 * @see Class
 */
public final class WhatIsNewInClass<T>
{
  /**
   * Example call to new method {@link Class#forName(Module, String)}.
   * @since 9
   * @see Class#forName(Module, String)
   */
  public static Class<?> forName(Module module, String name)
  {
    Class<?> result = Class.forName(module, name);
    return result;
  }

  /**
   * Example call to new method {@link Class#getModule()}.
   * @since 9
   * @see Class#getModule()
   */
  public Module getModule()
  {
    Class<T> testee = $$$();

    Module result = testee.getModule();
    return result;
  }

  /**
   * Example call to new method {@link Class#getPackageName()}.
   * @since 9
   * @see Class#getPackageName()
   */
  public String getPackageName()
  {
    Class<T> testee = $$$();

    String result = testee.getPackageName();
    return result;
  }

  private Class $$$()
  {
    return null;
  }
}
