package whatisnewin.javax.swing.text;

import javax.swing.text.WrappedPlainView;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link WrappedPlainView}
 * that were newly introduced in Java version 9.<br>
 *
 * {@link WrappedPlainView} is an old class but has new fields, constructors or methods.
 * @since UNDEFINED
 * @see WrappedPlainView
 */
public final class WhatIsNewInWrappedPlainView
{
}
