package whatisnewin.jdk.jshell;

import jdk.jshell.EvalException;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link EvalException}
 * that were newly introduced in Java version 9.<br>
 *
 * {@link EvalException} is a completely new class.
 * @since 9
 * @see EvalException
 */
public final class WhatIsNewInEvalException
{
  /**
   * Example call to new method {@link EvalException#getExceptionClassName()}.
   * @since 9
   * @see EvalException#getExceptionClassName()
   */
  public String getExceptionClassName()
  {
    EvalException testee = $$$();

    String result = testee.getExceptionClassName();
    return result;
  }

  private EvalException $$$()
  {
    return null;
  }
}
